### PR TITLE
Handle extension functions when validating @Binds methods with generateDaggerFactories

### LINKED ISSUE #661: BindsMethodValidator does not account for extension functions
When using `generateDaggerFactories`, this results in anvil failing to compile for a @Binds extension function with no parameters (when Dagger passes), and to pass for a @Binds extension function with a parameter (when Dagger fails).

Thanks @efemoney for [raising the extension use-case](https://github.com/square/anvil/pull/654#issuecomment-1324879737).

### PR DESCRIPTION
**Pull request by JoelWilcox**
Fixes #661

### CODE REVIEW

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt [hunk 1]
```diff
@@ -164,6 +194,30 @@ class BindsMethodValidatorTest(
...
+      interface Bar
+
+      @Module
+      abstract class BarModule {
+        @Binds
+        abstract fun Foo.bindsBar(): Bar
+      }
+      """
+    ) {
+      assertThat(exitCode).isEqualTo(OK)
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:217]: I'm not sure what you're testing here. Remove Anvil and the Dagger annotation processor from the build and the test would be green no matter what. Do you want to add a Dagger component to verify the binding method works?

Also, Anvil isn't doing anything with binding methods. There's also no Anvil annotation present in this entire test. It's a no-op at the moment.

Comment (JoelWilcox) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:217]: This is testing that our @Binds validation logic doesn't fail for a valid use-case; without the changes to `BindsMethodValidator` in this PR, this test fails because we would see that there was no parameter and throw an exception, while Dagger would compile successfully. Does that make sense, or do you think this is not worth including? For the purposes of this test it doesn't seem like including a Dagger component is necessary ; or at least, it's not clear why that would be needed here but not the other test cases. Open to being convinced otherwise :)

Comment (vRallev) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:217]: I guess it doesn't hurt. I suggested to add a component and make sure that the binding works, to give this test more meaning in the sense: hey, here's a binding method and it works at runtime with Anvil or Dagger. I've done this at a few other places.

**Review by vRallev — APPROVED** [review]

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt (hunk 1 above)
Comment (JoelWilcox) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:217]: Gotcha, that makes sense; I went ahead and added it to help with that clarity.

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt [hunk 2]
```diff
@@ -164,14 +194,56 @@ class BindsMethodValidatorTest(
...
+    compile(
+      """
+      package com.squareup.test
+
+      import dagger.Component
+      import javax.inject.Singleton
+
+      @Component(modules = [BarModule::class])
+      @Singleton
+      interface ComponentInterface
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:229]:
```suggestion
      interface ComponentInterface {
        fun bar(): Bar
      }
```
Otherwise Dagger won't care about the binding (or in different words, you could remove the Dagger module from the component and it still would compile).

Comment (JoelWilcox) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt]: Good catch 👍

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt [hunk 3]
```diff
@@ -164,14 +194,58 @@ class BindsMethodValidatorTest(
...
+
+    compile(
+      """
+      package com.squareup.test
+
+      import dagger.Component
+      import javax.inject.Singleton
+
+      @Component(modules = [BarModule::class])
+      @Singleton
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:228]: Super nit, but the `@Singleton` isn't needed.

**Review by vRallev — APPROVED** [review]
👍🏻 LGTM

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt (hunk 3 above)
Comment (JoelWilcox) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:228]: Will make a mental note to remove separately :D, want to get this in before merging the release updates
