### PR TITLE
Fix crash for inner classes starting with a lowercase character

### LINKED ISSUE #96: Factory generation: nested class with lowercase name
Anvil: 2.0,2

Reproducer:
```
class MyClass @Inject constructor(a: asg) {
  class asg @Inject constructor()
}
```

Exception:
```
e: java.lang.IllegalArgumentException: couldn't make a guess for com.example.myapplication.MyClass.asg
        at com.squareup.kotlinpoet.ClassName$Companion.bestGuess(TypeName.kt:465)
        at com.squareup.anvil.compiler.codegen.KotlinPoetKt.requireTypeName(KotlinPoet.kt:65)
        at com.squareup.anvil.compiler.codegen.KotlinPoetKt.mapToParameter(KotlinPoet.kt:110)
        at com.squareup.anvil.compiler.codegen.dagger.InjectConstructorFactoryGenerator.generateFactoryClass(InjectConstructorFactoryGenerator.kt:63)
```

### PR DESCRIPTION
**Pull request by vRallev**
Support inner classes starting with a lowercase character when generating factories for inject constructors.

Fixes #96

### CODE REVIEW

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt [hunk 1]
```diff
@@ -62,7 +62,7 @@ internal fun KtCallableDeclaration.requireTypeName(
       ?: typeReference.fqNameOrNull(module)
       ?: return typeVariableName()
 
-  return ClassName.bestGuess(fqNameForGuess.asString())
+  return fqNameForGuess.asTypeName()
```
Comment (zach-klippenstein) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt:65]: Not obvious how this was broken or why this fixes it, were we doing something wrong or is this working around another bug?

**Review by zach-klippenstein — APPROVED** [review]
