### PR TITLE
fall back to PSI parsing for BindingModuleGenerator

### LINKED ISSUE #310: PsiUtils' requireClassDescriptor fails to resolve generated types
Given this generated class:

``` Kotlin
@ContributesBinding(AppScope::class)
class GeneratedFooImpl @Inject constructor() : Foo
```

Both versions of `requireClassDescriptor` will fail to resolve `GeneratedFooImpl`.  This happens with any of the contributes/merge generators.

The new `RealAnvilModuleDescriptor` is being used, but it doesn't do any good since we're trying to get the `ClassDescriptor` instead of just an `FqName`.

Some `requireClassDescriptor` calls can be replaced with existing Psi calls, like when getting the scope argument in `BindingGenerator`.  `KtClassOrObject.checkClassExtendsBoundType` seems much more awkward, though, since that's trying to resolve super types.

### PR DESCRIPTION
**Pull request by RBusarow**
fixes #310

### CODE REVIEW

File: integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt [hunk 1]
```diff
@@ -66,18 +66,18 @@ class TestCodeGenerator : CodeGenerator {
           interface ContributedModule 
         """.trimIndent()
 
-        // This snippet is helpful for testing #310, which is still failing.
+        // This snippet is helpful for testing #310.
```
Comment (vRallev) [inline integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt:69]: 🎉

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt [hunk 2]
```diff
@@ -93,38 +94,41 @@ public fun ClassReference.allSuperTypeClassReferences(
...
-              ?.asSequence()
-              ?.map { module.requireClassReference(it.fqNameSafe) }
-          }
-        }
-      }
+      .mapNotNull { classRef -> classRef.directSuperClassReferences(module) }
       .flatten()
       .takeIf { it.firstOrNull() != null }
   }.flatten()
     .distinctBy { it.fqName }
```
Comment (vRallev) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt:109]: What I meant earlier was the suggestion below and always use the `sequenceOf(this)` as initial value.
```suggestion
  }
    .drop(if (includeSelf) 0 else 1)
    .flatten()
    .distinctBy { it.fqName }
```

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt [hunk 3]
```diff
@@ -93,38 +94,41 @@ public fun ClassReference.allSuperTypeClassReferences(
...
 }
 
+@ExperimentalAnvilApi
+public fun ClassReference.directSuperClassReferences(
+  module: ModuleDescriptor
+): Sequence<ClassReference> {
+
```
Comment (vRallev) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt:116]: Nit: unnecessary empty line.
```suggestion
```

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt [hunk 4]
```diff
@@ -93,38 +94,41 @@ public fun ClassReference.allSuperTypeClassReferences(
...
+  return when (this) {
+    is Descriptor -> {
+      clazz.directSuperClassAndInterfaces()
+        .asSequence()
+        .map { module.requireClassReference(it.fqNameSafe) }
+    }
+    is Psi -> {
+      clazz.superTypeListEntries
+        .map { it.requireFqName(module) }
+        .asSequence()
```
Comment (vRallev) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt:126]: Move the `asSequence()` operator one line up.
```suggestion
        .asSequence()
        .map { it.requireFqName(module) }
```

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt [hunk 5]
```diff
@@ -144,3 +148,38 @@ public fun ClassReference.indexOfTypeParameter(parameterName: String): Int {
...
+@ExperimentalAnvilApi
+public fun ClassReference.qualifiers(
+  module: ModuleDescriptor
+): List<AnnotationSpec> {
+  return when (this) {
+    is Descriptor -> {
+      clazz.annotations
+        .filter { it.isQualifier() }
+        .map { it.toAnnotationSpec(module) }
+    }
```
Comment (vRallev) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt:178]: The curly braces here and at many other places are redundant. We usually prefer not to have them, if they aren't required. It's not dangerous to omit them, because you use `when` as an expression. I'd be in favor of removing them everywhere where not needed. But it's not a hill I would die on.

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt [hunk 6]
```diff
@@ -483,6 +487,11 @@ public fun KtClassOrObject.properties(
   includeCompanionObjects: Boolean
 ): List<KtProperty> = classBodies(includeCompanionObjects).flatMap { it.properties }
 
+@ExperimentalAnvilApi
+public fun KtClassOrObject.isObject(): Boolean {
+  return this is KtObjectDeclaration
+}
```
Comment (vRallev) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt:493]: Nit: expression?
```suggestion
public fun KtClassOrObject.isObject(): Boolean = this is KtObjectDeclaration
```

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt [hunk 7]
```diff
@@ -93,38 +94,41 @@ public fun ClassReference.allSuperTypeClassReferences(
...
-          }
-          is Descriptor -> {
-            classRef.clazz.directSuperClassAndInterfaces()
-              .takeIf { it.isNotEmpty() }
-              ?.asSequence()
-              ?.map { module.requireClassReference(it.fqNameSafe) }
-          }
-        }
-      }
+      .mapNotNull { classRef -> classRef.directSuperClassReferences(module) }
```
Comment (vRallev) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt:105]: This can be null.
```suggestion
      .map { classRef -> classRef.directSuperClassReferences(module) }
```

**Review by vRallev — COMMENTED** [review]
This PR is awesome. There are mostly nits I'd address.

**Review by vRallev — APPROVED** [review]
