### PR TITLE
Fix crashes when classes don't use any package. 

### LINKED ISSUE #227: Top-level classes throw an error
I have a component in my module's `src/main/test` source-set as so: 

```kotlin
@[Singleton AppComponent MergeComponent(scope = AppComponent::class)]
interface DigitalWalletTestComponent {
}
```

The other files in the module are prod sources that all contribute to `@WalletScope`, e.g. `@[Module ContributesTo(AppComponent::class)]`

When running `:module:assembleDebutUnitTestSources`, I get an error in the `kaptGenerateStubsDebugUnitTestKotlin` task: 

```
e: java.lang.IllegalArgumentException: Can't escape identifier `<root>` because it contains illegal characters: <>
	at com.squareup.kotlinpoet.UtilKt.failIfEscapeInvalid(Util.kt:261)
	at com.squareup.kotlinpoet.UtilKt.escapeIfNecessary(Util.kt:270)
	at com.squareup.kotlinpoet.UtilKt.escapeIfNecessary$default(Util.kt:267)
	at com.squareup.kotlinpoet.UtilKt$escapeSegmentsIfNecessary$2.invoke(Util.kt:293)
	at com.squareup.kotlinpoet.UtilKt$escapeSegmentsIfNecessary$2.invoke(Util.kt)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3324)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3341)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3340)
	at com.squareup.kotlinpoet.UtilKt.escapeSegmentsIfNecessary(Util.kt:293)
	at com.squareup.kotlinpoet.UtilKt.escapeSegmentsIfNecessary$default(Util.kt:291)
	at com.squareup.kotlinpoet.FileSpec.emit(FileSpec.kt:138)
	at com.squareup.kotlinpoet.FileSpec.writeTo(FileSpec.kt:65)
	at com.squareup.anvil.compiler.codegen.KotlinPoetKt.writeToString(KotlinPoet.kt:329)
	at com.squareup.anvil.compiler.codegen.KotlinPoetKt.buildFile(KotlinPoet.kt:351)
	at com.squareup.anvil.compiler.codegen.BindingModuleGenerator.daggerModuleContent(BindingModuleGenerator.kt:349)
	at com.squareup.anvil.compiler.codegen.BindingModuleGenerator.generateCode(BindingModuleGenerator.kt:135)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension$analysisCompleted$2.invoke(CodeGenerationExtension.kt:57)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:62)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$invokeExtensionsOnAnalysisComplete(TopDownAnalyzerFacadeForJVM.kt:108)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:118)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:85)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:517)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:508)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:114)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:508)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:188)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1575)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by vRallev**
The compiler APIs return "<root>" as fully qualified name for the root package, but we want to default to an empty string instead.

Fixes #227

### CODE REVIEW

File: compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt [hunk 1]
```diff
@@ -258,3 +258,21 @@ internal fun AnnotationDescriptor.requireClass(): ClassDescriptor {
...
+internal fun FqName.safePackageString(
+  dotPrefix: Boolean = false,
+  dotSuffix: Boolean = true
+): String =
+  if (isRoot) {
+    ""
+  } else {
+    val prefix = if (dotPrefix) "." else ""
+    val suffix = if (dotSuffix) "." else ""
+    "$prefix$this$suffix"
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt:277]: This looks awkward, is there a more idiomatic way that's also readable?

Comment (0xMatthewGroves) [reply compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt:277]: Hard to say without having some sample input to look at. I assume some instances return something like .com.squareup.foo and some return com.squareup.bar.

Since your usages of safePackageString always include a suffix, I'd remove that as a parameterized option. Also, you can detect if the string is already prefixed with a dot and add it if not, since that appears to be the intended purpose. That'll clean up your API since you'll take care of it via code instead of having the dev determine proper usage.

`
internal fun FqName.safePackageString(): String =
      if(isRoot) {
          ""
      } else {
         ".$this.removeSurrounding(".")."
       }     
`

**Review by 0xMatthewGroves — APPROVED** [review]

File: compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt (hunk 1 above)
Comment (vRallev) [reply compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt:277]: The string is never prefixed with a dot. The two parameters make string templates easier to use. Imagine `prefix.package.${realPackage}.suffix`. Notice that for the root package this would result in `prefix.package..suffix`, which is annoying to handle. Therefore, this method accepts two parameters whether there is prefix or suffix for the template.
