### PR TITLE
Validate @Binds methods when generating dagger factories

### LINKED ISSUE #649: @Binds are not validated with `generateDaggerFactories`
With pure dagger this will lead to a compilation error:

```kotlin
@Module
abstract class OTestModule {

    @Binds
    abstract fun testBinding(impl: Context): StringBuilder
}
```

But when `generateDaggerFactories` is enabled, compilation is successful and we get an error during runtime. 

It would be great to get a compilation failure also with `generateDaggerFactories` enabled.

### PR DESCRIPTION
**Pull request by JoelWilcox**
Fixes #649

### CODE REVIEW

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt [hunk 1]
```diff
@@ -0,0 +1,165 @@
...
+      interface Bar
+
+      @Module
+      abstract class BarModule {
+        @Binds
+        abstract fun bindsBar(impl: Foo): Bar
+      }
+      """
+    ) {
+      assertThat(exitCode).isEqualTo(COMPILATION_ERROR)
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt:49]: There's a shortcut: `assertThat(exitCode).isError()`. In all these instances you should also verify the error message to ensure that the correct error is printed. This is quite important.

**Review by vRallev — CHANGES_REQUESTED** [review]

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt (hunk 1 above)
Comment (JoelWilcox) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt]: Good catch, updated now including error messages updated to exactly match Dagger's error messages.

**Review by vRallev — APPROVED** [review]
