### PR TITLE
Properly parse the `FqName` if the type reference is an inner class.

### LINKED ISSUE #479: Unable to generate contributed subcomponent with factory
I've got another one when generating a `@ContributesSubcomponent` with a `ParentComponent` inside.

```

@ContributesSubcomponent(
  scope = TrainingScope::class,
  parentScope = Singleton::class
)
public interface NavEntryTrainingScopeComponent {
  @ContributesSubcomponent.Factory
  public interface Factory {
    public fun create(): NavEntryTrainingScopeComponent
  }

  @ContributesTo(Singleton::class)
  public interface ParentComponent {
    public fun getNavEntryTrainingScopeComponent(): Factory
  }
}
```

Error:

```
e: com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't find return type for com.freeletics.app.NavEntryTrainingScopeComponent.ParentComponent.getNavEntryTrainingScopeComponent.
File is unknown

        at com.squareup.anvil.compiler.internal.FunctionReferenceKt.returnType(FunctionReference.kt:90)
        at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.findParentComponentInterface(ContributesSubcomponentHandlerGenerator.kt:363)
        at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.generateParentComponent(ContributesSubcomponentHandlerGenerator.kt:296)
        at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.access$generateParentComponent(ContributesSubcomponentHandlerGenerator.kt:89)
        at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator$generateCode$6$content$1.invoke(ContributesSubcomponentHandlerGenerator.kt:232)
        at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator$generateCode$6$content$1.invoke(ContributesSubcomponentHandlerGenerator.kt:197)
        at com.squareup.anvil.compiler.internal.KotlinPoetUtilsKt.buildFile(KotlinPoetUtils.kt:374)
        at com.squareup.anvil.compiler.internal.KotlinPoetUtilsKt.buildFile$default(KotlinPoetUtils.kt:363)
        at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.generateCode(ContributesSubcomponentHandlerGenerator.kt:197)
        at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted$generateCode(CodeGenerationExtension.kt:96)
        at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:136)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:122)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
        at jdk.internal.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Let me know if I should move this to a separate issue.

Update: this one works when I generate `ParentComponent` as a top level class in the same file, but it looks like Anvil also generates a `ParentComponent` in that case.

_Originally posted by @gabrielittner in https://github.com/square/anvil/issues/477#issuecomment-1025167831_

### PR DESCRIPTION
**Pull request by vRallev**
Fixes #479

### CODE REVIEW

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt [hunk 1]
```diff
@@ -428,6 +428,14 @@ public fun PsiElement.requireFqName(
       }
     }
 
+  // Check if it's an inner class of this file. A common case is return types of functions for
+  // inner classes, which require no import. Walk up the inner class hierarchy.
+  parents
```
Comment (RBusarow) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt:433]: This looked very familiar to me, because of `declarationsWithinScope` which is defined just below this function.  It _should have_ caught this edge case, but I missed an edge case.

The problem is that the existing function uses `it.children.filterIsInstance<KtNamedDeclaration>() + it` instead of `it.collectDescendantsOfType<KtNamedDeclaration>() + it`.

If `declarationsWithinScope()` is updated, then this addition shouldn't be necessary.  On the other hand, if this code is here, then the logic which calls `declarationsWithinScope()` isn't necessary.

Comment (vRallev) [reply compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt:433]: Oh, I wasn't aware. I'm in favor of keeping the new code. I'm a little unsure why you added the extension on `PsiElement`. Because of that resolving the FqName seems to involve more operations. `module.resolveFqNameOrNull(it)` is one of heavier functions.

Since we only care about classes or objects, I think it's safe to filter for that. I updated the code and used `collectDescendantsOfType`. That'a nice utility.

**Review by RBusarow — APPROVED** [review]
