### PR TITLE
Fix the absolute paths as inputs for Kapt and Kotlin compile tasks.

### LINKED ISSUE #65: Usage of absolute path as input
Recently after comparing build scans produced on developer machine and CI node we noticed following:
> Input 'kotlinCompile.com.squareup.anvil.compiler.src-gen-dir' is in both builds but the values are different.

This produces remote build cache misses for following tasks as paths are different:
- `org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask`
- `org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask`
- `org.jetbrains.kotlin.gradle.tasks.KotlinCompileWithWorkers`

I took a look in the source code and found this line: https://github.com/square/anvil/blob/9fb3c5f5b8a5134dd97d21d740271dcb276c6e0c/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt#L46 that returns absolute path to the Kotlin plugin. Kotlin plugin itself sets this as task inputs via https://github.com/JetBrains/kotlin/blob/34b55dbeb3a65b39b3585a646b5a0d2b1ce4dd96/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt#L1078

I am not sure what proper fix should be. Probably either using `srcGenDir.relativeTo(project.buildDir)` or asking Kotlin team to add relative `kind` type to [FilesSubpluginOptions](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin-api/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinGradleSubplugin.kt#L36).

### PR DESCRIPTION
**Pull request by vRallev**
Fixes #65

### CODE REVIEW

File: gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt [hunk 1]
```diff
@@ -50,10 +53,17 @@ class AnvilSubplugin : KotlinGradleSubplugin<AbstractCompile> {
...
+      val relativePath = srcGenDir.relativeTo(project.buildDir).path
+
+      project.tasks.withType(KotlinCompile::class.java) { task ->
+        task.inputs.property(key, relativePath)
+      }
+      project.tasks.withType(KaptTask::class.java) { task ->
+        // We don't apply the compiler plugin for KaptTasks. But for some reason the Kotlin Gradle
+        // plugin copies the inputs with the "kotlinCompile" prefix.
+        task.inputs.property("kotlinCompile.$key", relativePath)
+      }
```
Comment (vRallev) [inline gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt:66]: This used to be way more dynamic, but I was seeing strange build errors in CI only. No idea what happened.
```kotlin
      val key = "${getCompilerPluginId()}.${srcGenDirOption.key}"

      project.tasks
          .filter { it is KotlinCompile || it is KaptTask }
          .forEach { task ->
            task.inputs.properties
                .filter { it.key.contains(key) && it.value == srcGenDirPath }
                .forEach {
                  task.inputs.property(it.key, srcGenDir.relativeTo(project.buildDir).path)
                }
          }
```
This new solution is goo enough.

**Review by zach-klippenstein — APPROVED** [review]

**Comment by vRallev** [comment]
I'm hesitant to start writing Groovy :-/

**Comment by runningcode** [comment]
It is not required that the test be in groovy, you may write it in whichever language you please. That was just an example I had. :) 
Here is a relocatability test in Kotlin if that helps. https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/integration-test/application/src/test/java/com/android/build/gradle/integration/cacheability/CacheabilityTest.kt#181
