### PR TITLE
Print a better user-friendlier error message for Dagger provider methods with an implicit return type.

### LINKED ISSUE #124: Improve error message for implicit return types
Provider methods for Dagger modules require an explicit return type. The current error message isn't userfriendly at all:
```
e: com.squareup.anvil.compiler.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't obtain type reference.
File being compiled: (41,5) in /../File.kt
```

### PR DESCRIPTION
**Pull request by vRallev**
Fixes #124

### CODE REVIEW

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt [hunk 1]
```diff
@@ -2249,6 +2250,28 @@ public final class DaggerComponentInterface implements ComponentInterface {
     }
   }
 
+  @Test fun `a return type for a provider method is required`() {
```
Comment (cdeange) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt:2253]: I love these kinds of integration tests. So easy to read and comprehend.

**Review by cdeange — APPROVED** [review]

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt (hunk 1 above)
Comment (vRallev) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt:2253]: 😇
