### PR TITLE
Extend `ClassReference` and introduce more common APIs …

### LINKED ISSUE #462: [compiler-api] Compilation Error in generated class when using custom code generator
I wrote a custom code generator using the `compiler-api` to generate subcomponents for Activities with ContributeSubComponent annotation, but I keep getting the following compilation error

```
e: com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve class for com.sample.anvil.FailingClass_AnvilSubComponent
File is unknown

	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireClassDescriptor(PsiUtils.kt:765)
	at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.findFactoryClass(ContributesSubcomponentHandlerGenerator.kt:387)
	at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.generateCode(ContributesSubcomponentHandlerGenerator.kt:206)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted$generateCode(CodeGenerationExtension.kt:93)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:107)
```

I noticed that interface is being generated properly with all the annotations and methods in place. Also, if I add the class manually then it works perfectly and compilation doesn't fail. 

I am attaching a sample project with the above use case. Thanks in advance :)
[FailingAnvil.zip](https://github.com/square/anvil/files/7894865/FailingAnvil.zip)

### PR DESCRIPTION
**Pull request by vRallev**
…for PSI and descriptor compiler APIs. This is required to make parsing and generating code easier.

Use this new functionality in contributed subcomponent generator and avoid hardcoding descriptor APIs.

Fixes #462

### CODE REVIEW

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt [hunk 1]
```diff
@@ -350,41 +349,40 @@ internal class ContributesSubcomponentHandlerGenerator(
...
-    val contributionDescriptor = contributionFqName.requireClassDescriptor(module)
 
-    val contributedInnerComponentInterfaces = contributionDescriptor.unsubstitutedMemberScope
-      .getContributedDescriptors(kindFilter = CLASSIFIERS)
-      .filterIsInstance<ClassDescriptor>()
-      .filter { DescriptorUtils.isInterface(it) }
-      .filter {
-        val annotation = it.annotationOrNull(contributesToFqName, contribution.parentScope)
-        annotation != null
+    val contributedInnerComponentInterfaces = contribution.classReference
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt:353]: Note that we used descriptor APIs before, and this was failing when a subcomponent was generated through a code generator. With the abstract API this isn't an issue anymore.

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt [hunk 2]
```diff
@@ -186,7 +186,7 @@ internal class ContributesSubcomponentHandlerGenerator(
 
     val newContributions = contributions
       .flatMap { contribution ->
-        newTriggers
+        triggers
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt:189]: I actually made this change to fix the referenced bug, but it introduced regressions and wasn't the proper fix.

File: compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt [hunk 3]
```diff
@@ -1547,6 +1558,76 @@ class ContributesSubcomponentHandlerGeneratorTest {
     }
   }
 
+  @Test fun `an @ContributeSubcomponent class can be generated`() {
+    val codeGenerator = object : CodeGenerator {
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt:1562]: Custom code generator in unit tests!

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/AnnotationReference.kt [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+
+@ExperimentalAnvilApi
+public fun AnnotationDescriptor.toAnnotationReference(): Descriptor {
+  return Descriptor(this, requireClass().toClassReference())
+}
+
+@ExperimentalAnvilApi
+public fun AnnotationReference.scope(
+  module: ModuleDescriptor,
+  parameterIndex: Int = 0
```
Comment (0xMatthewGroves) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/AnnotationReference.kt:60]: In what scenario would you want to directly call this method with an overridden parameterIndex? This seems a bit clunky, because the caller doesn't know that the parameter does nothing if it's being called on a Descriptor object.

Comment (0xMatthewGroves) [reply compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/AnnotationReference.kt:60]: Splitting them to two separate extensions might be a bit cleaner in this case. That way the Psi specific extension can have extra kdoc explaining what that's for.

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt [hunk 5]
```diff
@@ -225,3 +248,48 @@ public fun ClassReference.isInterface(): Boolean = when (this) {
...
+    is Psi -> clazz.annotationEntries.map { it.toAnnotationReference(module) }
+    is Descriptor -> clazz.annotations.map { it.toAnnotationReference() }
+  }
+
+@ExperimentalAnvilApi
+public fun ClassReference.functions(): List<FunctionReference> =
+  when (this) {
+    is Psi ->
+      clazz
+        .functions(includeCompanionObjects = false)
```
Comment (0xMatthewGroves) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt:270]: Wow, cool.

**Review by 0xMatthewGroves — APPROVED** [review]

**Review by RBusarow — APPROVED** [review]

File: compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt (hunk 3 above)
Comment (RBusarow) [reply compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt:1562]: Between this (which forces Psi resolution) and passing in the previous compilation result (which forces Descriptor resolution), there's nothing we can't _easily_ test.  I love it!

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/AnnotationReference.kt (hunk 4 above)
Comment (vRallev) [reply compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/AnnotationReference.kt:60]: Well, that's the whole point that there aren't supposed to be two functions. You don't need to specify the parameter with the default, but I wanted to leave the door open for external code generators and custom annotations. For example, when we read the `replaces` attribute, then the index will be different depending on the annotation.
