### PR TITLE
Strip out backticks from type names before attempting type resolution

### LINKED ISSUE #641: Anvil cannot resolve types whose names are wrapped in backticks (like from KopyKat)
I ran into this while trying out [KopyKat](https://github.com/kopykat-kt/kopykat).

If KopyKat's added to a module which is also using Anvil's `BindingModuleGenerator`, you get this:

```
e: com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve FqName `SomeDataClass$DslMarker` for Psi element: `SomeDataClass$DslMarker`
File being compiled: [...].SomeDataClass$Mutable.kt

        at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:288)
        at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireFqName(PsiUtils.kt:139)
        at com.squareup.anvil.compiler.internal.reference.AnnotationReferenceKt.toAnnotationReference(AnnotationReference.kt:227)
        at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi$annotations$2.invoke(ClassReference.kt:146)
        at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi$annotations$2.invoke(ClassReference.kt:145)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.squareup.anvil.compiler.internal.reference.ClassReference$Psi.getAnnotations(ClassReference.kt:145)
        at com.squareup.anvil.compiler.internal.reference.AnnotatedReference$DefaultImpls.isAnnotatedWith(AnnotatedReference.kt:14)
        at com.squareup.anvil.compiler.internal.reference.ClassReference.isAnnotatedWith(ClassReference.kt:51)
        at com.squareup.anvil.compiler.codegen.BindingModuleGenerator.generateCode(BindingModuleGenerator.kt:74)
        at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted$generateCode(CodeGenerationExtension.kt:104)
        at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:139)
        [...]
```

The annotation class it's trying to resolve is declared like this:

```kotlin
@DslMarker
public annotation class `SomeDataClass$DslMarker`
```

The problem is that the PSI resolve function is trying to resolve the FqName with backticks included, like: ``com.example.`SomeDataClass$DslMarker` ``. But in order to actually resolve the name inside a `ModuleDescriptor`, we need to strip out the backticks.

### PR DESCRIPTION
**Pull request by RBusarow**
fixes #641

### CODE REVIEW

File: compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt [hunk 1]
```diff
@@ -85,40 +85,34 @@ public fun PsiElement.requireFqName(
...
-
-        // Sometimes a KtUserType is a fully qualified name. Give it a try and return early.
-        if (text.contains(".") && text[0].isLowerCase()) {
-          FqName(text).takeIf { it.canResolveFqName(module) }
-            ?.let { return it }
-        }
-
-        // We can't use referencedName here. For inner classes like "Outer.Inner" it would only
-        // return "Inner", whereas text returns "Outer.Inner", what we expect.
-        text
```
Comment (RBusarow) [inline compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt:121]: This is handled by the `qualifierText != null` condition now, with `"$qualifierText.$className"`.

**Review by JoelWilcox — APPROVED** [review]
