### PR TITLE
fix where clauses and generic type bounds in injected classes

### LINKED ISSUE #251: where clauses not handled correctly
```kotlin
class SKTokenSelectDelegateImpl<SCDMBinder> @Inject constructor(
  private val prefsManagerLazy: Lazy<PrefsManager>,
  private val slackConnectDmViewBinderLazy: Lazy<SCDMBinder>,
  private val tokenResultsUserViewBinderLazy: Lazy<TokenResultsUserViewBinder>,
  @AndroidIncreaseMpdmLimitFeatureFlag private val increaseMpdmLimit: Boolean,
) : SKTokenSelectDelegate where SCDMBinder : SKListCustomViewBinder, SCDMBinder : SKTokenSlackConnectDmBinder {
```

Generates

```kotlin
public class SKTokenSelectDelegateImpl_Factory<SCDMBinder>(
  private val param0: Provider<@JvmSuppressWildcards PrefsManager>,
  private val param1: Provider<@JvmSuppressWildcards SCDMBinder>,
  private val param2: Provider<@JvmSuppressWildcards TokenResultsUserViewBinder>,
  private val param3: Provider<Boolean>
) : Factory<SKTokenSelectDelegateImpl<SCDMBinder>> {
```

the generated factory is missing the bounds on `SCDMBinder`

### LINKED ISSUE #253: factory generation fails when the injected class has a type variable bound by a generic type
source:
``` Kotlin
class InjectClass<T : List<String>> @Inject constructor(
  private val t: T
)
```

The generated factory should have a type variable of `T : List<String>`, but it's just `T : List`.

generated:
``` Kotlin
public class InjectClass_Factory<T : List>(
  private val param0: Provider<T>
) : Factory<InjectClass<T>> {
  public override fun `get`(): InjectClass<T> = newInstance(param0.get())

  public companion object {
    @JvmStatic
    public fun <T : List> create(param0: Provider<T>): InjectClass_Factory<T> =
        InjectClass_Factory<T>(param0)

    @JvmStatic
    public fun <T : List> newInstance(param0: T): InjectClass<T> = InjectClass<T>(param0)
  }
}
```

### PR DESCRIPTION
**Pull request by RBusarow**
fixes #253 
fixes #251

### CODE REVIEW

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt [hunk 1]
```diff
@@ -402,6 +405,49 @@ internal fun ModuleDescriptor.findClassOrTypeAlias(
...
+  // It's also technically possible to have one constraint in the type parameter spot, like this:
+  // class MyClass<T : Any> where T : Set<*>, T : MutableCollection<*>
+  // Merge both groups of type parameters in order to get the full list of bounds.
+  val boundsByVariableName = mutableMapOf<String, MutableList<TypeName>>()
+
+  typeParameterList
+    ?.parameters
+    ?.forEach { parameter ->
+
+      if (parameter.fqNameOrNull(module) == null) {
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt:421]: That if check could be a `.filter {..}`

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt [hunk 2]
```diff
@@ -402,6 +405,49 @@ internal fun ModuleDescriptor.findClassOrTypeAlias(
...
 }
 
+internal fun KtClassOrObject.typeVariableNames(
+  module: ModuleDescriptor
+): List<TypeVariableName> {
+  // Any type which is constrained in a `where` clause is also defined as a type parameter.
+  // It's also technically possible to have one constraint in the type parameter spot, like this:
+  // class MyClass<T : Any> where T : Set<*>, T : MutableCollection<*>
+  // Merge both groups of type parameters in order to get the full list of bounds.
+  val boundsByVariableName = mutableMapOf<String, MutableList<TypeName>>()
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt:415]: Appen `.withDefault { mutableListOf() }`, then you can replace the `getOrPut`s below with `getValue(variableName)`.

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt [hunk 3]
```diff
@@ -73,17 +72,7 @@ internal class AssistedInjectGenerator : PrivateCodeGenerator() {
...
-      ?.mapNotNull { parameter ->
-        val extendsBound = parameter.extendsBound?.fqNameOrNull(module)?.asClassName(module)
-        if (parameter.fqNameOrNull(module) == null) {
-          TypeVariableName(parameter.nameAsSafeName.asString(), listOfNotNull(extendsBound))
-        } else {
-          null
-        }
-      }
-      ?: emptyList()
+    val typeParameters = clazz.typeVariableNames(module)
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt:75]: Nice cleanup.

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt [hunk 4]
```diff
@@ -409,6 +409,106 @@ public final class AssistedServiceFactory_Impl<T extends CharSequence> implement
...
+      package com.squareup.test
+      
+      import dagger.assisted.Assisted
+      import dagger.assisted.AssistedFactory
+      import dagger.assisted.AssistedInject
+      
+      data class AssistedService<T> @AssistedInject constructor(
+        val int: Int,
+        @Assisted val stringBuilder: T
+      ) where T : Appendable, T : CharSequence {
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt:469]: Awesome!

**Review by vRallev — CHANGES_REQUESTED** [review]
Great PR, thank you! Only some minor nits that I'd like to see changed.

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt (hunk 2 above)
Comment (RBusarow) [reply compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt]: Unfortunately that doesn't work.  `withDefault { ... }` returns a default list, but doesn't actually do a `put` into to the map.  So after adding the `TypeName` to the default list, we'd still need to add a `put`.

Instead, I just used `associateTo` for the parameters.  Since any generic in the constraint list must also be at least named in the `parameters` list, we can still use `getValue` in the second `forEach`.

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt (hunk 1 above)
Comment (RBusarow) [reply compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt]: This is funny because I'd considered it after I made the PR, then decided I was nitpicking and should just leave it alone.  I should have gone with my first instinct. :)

**Review by vRallev — APPROVED** [review]

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt (hunk 2 above)
Comment (vRallev) [reply compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt]: Oh, I wasn't aware. Sounds good!
