### PR TITLE
fix member injection for multiple supers from a different module

### LINKED ISSUE #442: Still MemberInjectors issue for super classes in different Gradle project
@RBusarow 
I just tried latest SNAPSHOT, and we are closer!

I now see this when I try to build here:
https://github.com/JohnBuhanan/anvil-factory-generation-members-injector-issue

```
public class FeatureActivity1_MembersInjector(
  private val b1: Provider<B1>,
  private val b2: Provider<B2>,
  private val f1: Provider<F1>
) : MembersInjector<FeatureActivity1> {
  public override fun injectMembers(instance: FeatureActivity1): Unit {
    BaseActivity2_MembersInjector.injectB1(instance, b1.get())  <--- Should be BaseActivity1 I think?
    BaseActivity2_MembersInjector.injectB2(instance, b2.get())
    FeatureActivity1_MembersInjector.injectF1(instance, f1.get())
  }
...
```

### PR DESCRIPTION
**Pull request by RBusarow**
fixes #442

### CODE REVIEW

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt [hunk 1]
```diff
@@ -1627,6 +1627,276 @@ public final class InjectClass_MembersInjector<T, U, V> implements MembersInject
...
+      """
+    ) {
+      assertThat(exitCode).isEqualTo(OK)
+    }
+
+    compile(
+      """
+      package com.squareup.test
+
+      import com.squareup.test.Base1
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt:1655]: This import is not used. I think even `Base2` doesn't need to be imported because the files use the same package.

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt [hunk 2]
```diff
@@ -1627,6 +1627,276 @@ public final class InjectClass_MembersInjector<T, U, V> implements MembersInject
...
+      import com.squareup.test.Base2
```
Comment (vRallev) [inline compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt:1754]: Same here.

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt [hunk 3]
```diff
@@ -35,8 +36,31 @@ sealed interface Parameter {
...
 }
 
+/**
+ * Returns a name which is unique when compared to the [Parameter.originalName] of the
+ * [superParameters] argument.
+ *
+ * This mimics Dagger's method of unique naming.  If there are three parameters named "foo", the
+ * unique parameter names will be [foo, foo2, foo3].
+ */
+internal fun String.uniqueName(
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt:46]: Would `uniqueParameterName` a better function name?

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt [hunk 4]
```diff
@@ -35,8 +36,31 @@ sealed interface Parameter {
     }
 }
 
+/**
+ * Returns a name which is unique when compared to the [Parameter.originalName] of the
+ * [superParameters] argument.
+ *
+ * This mimics Dagger's method of unique naming.  If there are three parameters named "foo", the
+ * unique parameter names will be [foo, foo2, foo3].
```
Comment (vRallev) [inline compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt:44]: I struggled with the description first and couldn't understand why it's needed without looking at the tests added in this PR. First, when I read "parameter" I was thinking of constructor injection, but there can't be multiple parameters with the same name. It would help to mention that this is related to member injection and the same parameter names come from injected members in super types.

Comment (RBusarow) [reply compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt:48]: Great feedback, thanks!

File: compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt (hunk 1 above)
Comment (RBusarow) [reply compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt]: Yep, you're right.  Nice catch!

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt (hunk 3 above)
Comment (RBusarow) [reply compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt]: Definitely!  Especially considering that the receiver is just `String`, and it's top-level.

Thanks!

File: compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt (hunk 4 above)
Comment (vRallev) [reply compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt:48]: Perfect 👍🏻

**Review by vRallev — APPROVED** [review]
